FROM alpine:3.8

RUN apk add --no-cache --virtual build-essential build-base autoconf gcc cmake linux-headers libexecinfo-dev gnutls-dev bison
RUN apk add --no-cache vim bash openssl wget curl libcurl bzip2 git zip unzip

