FROM ubuntu:18.04

RUN apt-get update \
  && apt-get install -y build-essential autoconf gcc cmake \
  && apt-get install -y gnutls-dev bison libbison-dev libncurses-dev locales \
  && apt-get install -y libz-dev openssl libssl-dev gnupg \
  && apt-get install -y iputils-ping telnet curl wget bash vim zip unzip git
